
replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
#  tag: 9.4
  tag: 11-alpine
service:
  port: 5432
  type: ClusterIP

serviceAccount:
  create: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
